//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code9.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Code9.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Checked in.
        /// </summary>
        public static string CheckedIn {
            get {
                return ResourceManager.GetString("CheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Checked out.
        /// </summary>
        public static string Checkedout {
            get {
                return ResourceManager.GetString("Checkedout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn Your Store.
        /// </summary>
        public static string CheckInStore {
            get {
                return ResourceManager.GetString("CheckInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn.
        /// </summary>
        public static string CheckInTitle {
            get {
                return ResourceManager.GetString("CheckInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Your Store.
        /// </summary>
        public static string CheckOutStore {
            get {
                return ResourceManager.GetString("CheckOutStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOut.
        /// </summary>
        public static string CheckOutTitle {
            get {
                return ResourceManager.GetString("CheckOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen.
        /// </summary>
        public static string Citizen {
            get {
                return ResourceManager.GetString("Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspected as you contacted with an infected Person , please Quarantine your self 14 Days.
        /// </summary>
        public static string ContactedWithInfectedPerson {
            get {
                return ResourceManager.GetString("ContactedWithInfectedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong!.
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id and password are required.
        /// </summary>
        public static string IdAndPasswordRequired {
            get {
                return ResourceManager.GetString("IdAndPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infected.
        /// </summary>
        public static string Infected {
            get {
                return ResourceManager.GetString("Infected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infected Person visit your Shop , Your Trust status is Changed.
        /// </summary>
        public static string InfectedPersonVisitStore {
            get {
                return ResourceManager.GetString("InfectedPersonVisitStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Status Alert.
        /// </summary>
        public static string MedicalStatusAlertTitle {
            get {
                return ResourceManager.GetString("MedicalStatusAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Medical Status is changed to.
        /// </summary>
        public static string MedicalStatusIsChanged {
            get {
                return ResourceManager.GetString("MedicalStatusIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Body.
        /// </summary>
        public static string NotificationBody {
            get {
                return ResourceManager.GetString("NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct.
        /// </summary>
        public static string PasswordIsNotTrue {
            get {
                return ResourceManager.GetString("PasswordIsNotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please checkOut of this shop to checkIn again.
        /// </summary>
        public static string PleaseCheckOutOfShopToCheckInAgain {
            get {
                return ResourceManager.GetString("PleaseCheckOutOfShopToCheckInAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , please Quarantine your self 14 Days.
        /// </summary>
        public static string PleaseQuarantineYourSelf {
            get {
                return ResourceManager.GetString("PleaseQuarantineYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Is Already On This Status.
        /// </summary>
        public static string ShopIsAlreadyOnThisStatus {
            get {
                return ResourceManager.GetString("ShopIsAlreadyOnThisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Is Not Exist.
        /// </summary>
        public static string ShopIsNotExist {
            get {
                return ResourceManager.GetString("ShopIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Shop Status is changed to.
        /// </summary>
        public static string ShopStatusIsChanged {
            get {
                return ResourceManager.GetString("ShopStatusIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Is Changed To Trusted.
        /// </summary>
        public static string ShopStatusIsChangedToNormal {
            get {
                return ResourceManager.GetString("ShopStatusIsChangedToNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspected.
        /// </summary>
        public static string Suspected {
            get {
                return ResourceManager.GetString("Suspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Trust status is Normal Now.
        /// </summary>
        public static string TruststatusIsNormal {
            get {
                return ResourceManager.GetString("TruststatusIsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Already On This Status.
        /// </summary>
        public static string UserIsAlreadyOnThisStatus {
            get {
                return ResourceManager.GetString("UserIsAlreadyOnThisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Doesn&apos;t Have Permission.
        /// </summary>
        public static string UserIsNotHavePermission {
            get {
                return ResourceManager.GetString("UserIsNotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is Not Exist.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
    }
}
